apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: projjeffexternalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: projjeffsecretsstore
    kind: SecretStore
  target:
    name: projjeffsecret
    creationPolicy: Owner
  data:
  - secretKey: CLUSTER_TYPE
    remoteRef:
      key: proj/jeff/ProjApps             #AWS Secrets Manager secret name
      property: CLUSTER_TYPE              #AWS Secrets Manager secret key
  - secretKey: KC_ARGOCD_CLIENT_SECRET
    remoteRef:
      key: proj/jeff/ProjApps             #AWS Secrets Manager secret name
      property: KC_ARGOCD_CLIENT_SECRET   #AWS Secrets Manager secret key